[package]
name = "bund_stdlib_text_classifier"
version = "0.1.0"
edition = "2024"

[dependencies]
bayesic = "0.1.1"
bundcore = "0.4.0"
charabia = "0.9.7"
easy-error = "1.0.0"
growable-bloom-filter = "2.1.1"
lazy_static = "1.5.0"
rust_dynamic = "0.48.0"
